# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0004_auto_20160209_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfactor',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='toolbox.Platform', verbose_name=b'Platformen'),
        ),
    ]
